name: Docker

permissions:
  contents: read

on:
  push: {}
  pull_request: {}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0

      - name: Build Docker Image
        run: docker build -t proto-gen-go .
