name: Triage new issue
on:
  issues:
    types:
      - opened
      - transferred
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label triage
        uses: andymckay/labeler@e6c4322d0397f3240f0e7e30a33b5c5df2d39e90
        with:
          add-labels: "needs triage, needs refinement"
          ignore-if-labeled: false
